//! App command/query layer tests against an in-memory store.

use std::path::PathBuf;

use navigator_analysis::caller::HaploidCallerParams;
use navigator_analysis::coverage::CallableLociParams;
use navigator_app::{App, AppError};
use navigator_domain::workspace::{NewAlignment, NewProject, NewSequenceRun};
use navigator_store::Store;
use serde::{Deserialize, Serialize};

async fn app() -> App {
    App::new(Store::open_in_memory().await.unwrap())
}

/// Reuse the analysis crate's committed fixtures (workspace-relative).
fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../navigator-analysis/tests/fixtures")
}

/// Serializes the `NAVIGATOR_REFGENOME_DIR` env write (read once in `App::new`) so
/// parallel tests pointing the gateway cache at different temp dirs don't race.
static REF_ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// An `App` whose reference-gateway cache is `cache`. The store is opened first (async), then
/// the env write + `App::new` happen synchronously under the lock so the gateway captures the
/// right base dir without racing other tests.
async fn app_with_ref_cache(cache: &std::path::Path) -> App {
    let store = Store::open_in_memory().await.unwrap();
    let _g = REF_ENV_LOCK.lock().unwrap();
    std::env::set_var("NAVIGATOR_REFGENOME_DIR", cache);
    App::new(store)
}

#[tokio::test]
async fn import_str_profile_from_csv_round_trips() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap(); // no project needed

    // A small FTDNA-style marker export.
    let path = std::env::temp_dir().join(format!("str-{}.csv", subject.guid.0));
    std::fs::write(&path, "Marker,Value\nDYS393,13\nDYS390,24\nDYS385,11-14\n").unwrap();

    let profile = app
        .import_str_profile_from_csv(subject.guid, "Y-37", Some("FTDNA".into()), Some("DIRECT_TEST".into()), &path)
        .await
        .unwrap();
    assert_eq!(profile.panel_name, "Y-37");
    assert_eq!(profile.markers.len(), 3);

    let listed = app.list_str_profiles(subject.guid).await.unwrap();
    assert_eq!(listed.len(), 1);
    assert_eq!(listed[0].provider.as_deref(), Some("FTDNA"));
    assert_eq!(listed[0].markers[2].value, "11-14"); // multi-copy preserved through the store

    let _ = std::fs::remove_file(&path);
}

#[tokio::test]
async fn import_variants_from_csv_keeps_only_snps() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();

    let path = std::env::temp_dir().join(format!("variants-{}.csv", subject.guid.0));
    // header layout; one indel row that must be dropped (SNP-only)
    std::fs::write(&path, "contig,position,ref,alt,rsid,genotype\nchr1,1000,A,G,rs1,0/1\nchr1,2000,A,AT,rs2,0/1\nchrM,73,G,A,.,1/1\n").unwrap();

    let set = app
        .import_variants_from_file(subject.guid, &path, navigator_app::SourceType::Imported)
        .await
        .unwrap();
    assert_eq!(set.source_label, path.file_name().unwrap().to_string_lossy());
    assert_eq!(set.source_type, navigator_app::SourceType::Imported);
    assert_eq!(set.calls.len(), 2); // the A>AT indel dropped

    let listed = app.list_variant_sets(subject.guid).await.unwrap();
    assert_eq!(listed.len(), 1);
    assert_eq!(listed[0].calls[0].rs_id.as_deref(), Some("rs1"));
    assert_eq!(listed[0].calls[0].genotype.as_deref(), Some("0/1"));
    assert_eq!(listed[0].calls[1].rs_id, None); // "." normalized away

    let _ = std::fs::remove_file(&path);
}

#[tokio::test]
async fn import_chip_profile_detects_vendor_and_summarizes() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();

    let path = std::env::temp_dir().join(format!("chip-{}.txt", subject.guid.0));
    std::fs::write(
        &path,
        "# This data file generated by 23andMe\nrsid\tchromosome\tposition\tgenotype\n\
         rs1\t1\t100\tAA\nrs2\t1\t200\tAG\nrs3\t1\t300\t--\nrs4\tY\t400\tG\n",
    )
    .unwrap();

    // provider=None -> auto-detect from the header
    let profile = app.import_chip_profile_from_csv(subject.guid, None, None, &path).await.unwrap();
    assert_eq!(profile.provider, "23andMe");
    assert_eq!(profile.summary.total_markers_possible, 4);
    assert_eq!(profile.summary.total_markers_called, 3); // "--" no-call
    assert_eq!(profile.summary.y_markers_called, 1);
    assert_eq!(profile.summary.het_rate, Some(0.5)); // 1 het of 2 autosomal

    let listed = app.list_chip_profiles(subject.guid).await.unwrap();
    assert_eq!(listed.len(), 1);
    assert_eq!(listed[0].source_file_name.as_deref(), Some(path.file_name().unwrap().to_str().unwrap()));

    let _ = std::fs::remove_file(&path);
}

#[tokio::test]
async fn import_mtdna_fasta_round_trips() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();

    // 16,569 bp with two Ns.
    let mut body = "A".repeat(16_567);
    body.insert_str(100, "NN");
    let path = std::env::temp_dir().join(format!("mtdna-{}.fasta", subject.guid.0));
    std::fs::write(&path, format!(">sample mtDNA\n{body}\n")).unwrap();

    let seq = app.import_mtdna_from_fasta(subject.guid, &path).await.unwrap();
    assert_eq!(seq.length(), 16_569);
    assert_eq!(seq.n_count, 2);
    assert_eq!(seq.defline.as_deref(), Some("sample mtDNA"));

    let listed = app.list_mtdna_sequences(subject.guid).await.unwrap();
    assert_eq!(listed.len(), 1);
    assert_eq!(listed[0].sequence.len(), 16_569);

    // a too-short sequence is rejected
    let bad = std::env::temp_dir().join(format!("mtdna-bad-{}.fasta", subject.guid.0));
    std::fs::write(&bad, ">x\nACGT\n").unwrap();
    assert!(matches!(app.import_mtdna_from_fasta(subject.guid, &bad).await, Err(AppError::Import(_))));

    let _ = std::fs::remove_file(&path);
    let _ = std::fs::remove_file(&bad);
}

#[tokio::test]
async fn derive_mtdna_variants_vs_rcrs() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let dir = std::env::temp_dir();

    // A synthetic 16,569 bp "rCRS"; the sample differs at two positions.
    let reference = "A".repeat(16_569);
    let mut sample = reference.clone().into_bytes();
    sample[262] = b'G'; // position 263 A>G
    sample[749] = b'C'; // position 750 A>C
    let sample = String::from_utf8(sample).unwrap();

    let ref_path = dir.join(format!("rcrs-{}.fasta", subject.guid.0));
    let samp_path = dir.join(format!("mt-{}.fasta", subject.guid.0));
    std::fs::write(&ref_path, format!(">rCRS\n{reference}\n")).unwrap();
    std::fs::write(&samp_path, format!(">sample\n{sample}\n")).unwrap();

    let mt = app.import_mtdna_from_fasta(subject.guid, &samp_path).await.unwrap();
    let set = app.derive_mtdna_variants(mt.id, &ref_path).await.unwrap();
    assert_eq!(set.calls.len(), 2);
    assert_eq!(set.calls[0].contig, "rCRS");
    assert_eq!((set.calls[0].position, set.calls[0].reference.as_str(), set.calls[0].alternate.as_str()), (263, "A", "G"));
    assert_eq!((set.calls[1].position, set.calls[1].alternate.as_str()), (750, "C"));

    // it lands in the subject's variant sets
    assert_eq!(app.list_variant_sets(subject.guid).await.unwrap().len(), 1);

    for p in [ref_path, samp_path] {
        let _ = std::fs::remove_file(p);
    }
}

#[tokio::test]
async fn derive_mtdna_variants_detects_a_deletion() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let dir = std::env::temp_dir();

    // rCRS: A-runs around a 9-base landmark at positions 301-309; the sample lacks it. The
    // landmark is A-free so the flanking A-runs can't absorb any of it — the 9-base
    // deletion is unambiguous.
    let landmark = "CCCCCCCCC";
    let reference = format!("{}{}{}", "A".repeat(300), landmark, "A".repeat(16_569 - 309));
    let sample = "A".repeat(16_560);
    assert_eq!(reference.len(), 16_569);
    assert_eq!(sample.len(), 16_560);

    let ref_path = dir.join(format!("rcrs-del-{}.fasta", subject.guid.0));
    let samp_path = dir.join(format!("mt-del-{}.fasta", subject.guid.0));
    std::fs::write(&ref_path, format!(">rCRS\n{reference}\n")).unwrap();
    std::fs::write(&samp_path, format!(">sample\n{sample}\n")).unwrap();

    let mt = app.import_mtdna_from_fasta(subject.guid, &samp_path).await.unwrap();
    let set = app.derive_mtdna_variants(mt.id, &ref_path).await.unwrap();
    assert_eq!(set.calls.len(), 1);
    let del = &set.calls[0];
    assert_eq!(del.position, 301);
    assert_eq!(del.reference, landmark);
    assert_eq!(del.alternate, ""); // deletion: empty alt

    for p in [ref_path, samp_path] {
        let _ = std::fs::remove_file(p);
    }
}

#[tokio::test]
async fn assign_mtdna_haplogroup_ranks_best() {
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let dir = std::env::temp_dir();

    // Sample carries the tree's derived G at 263 and 750 (RSRS-anchored, no reference).
    let mut sample = "A".repeat(16_569).into_bytes();
    sample[262] = b'G'; // position 263
    sample[749] = b'G'; // position 750
    let sample = String::from_utf8(sample).unwrap();
    let samp_path = dir.join(format!("mt-hg-{}.fasta", subject.guid.0));
    std::fs::write(&samp_path, format!(">sample\n{sample}\n")).unwrap();
    let mt = app.import_mtdna_from_fasta(subject.guid, &samp_path).await.unwrap();

    let tree = r#"{"allNodes":{
        "1":{"haplogroupId":1,"name":"root","isRoot":true,"variants":[],"children":[2]},
        "2":{"haplogroupId":2,"name":"H","isRoot":false,"variants":[{"variant":"A263G","position":263,"ancestral":"A","derived":"G"}],"children":[3]},
        "3":{"haplogroupId":3,"name":"H2","isRoot":false,"variants":[{"variant":"A750G","position":750,"ancestral":"A","derived":"G"}],"children":[]}
    }}"#;

    let ranked = app.assign_mtdna_haplogroup_with_tree(mt.id, tree).await.unwrap().ranked;
    assert_eq!(ranked[0].name, "H2"); // carries both derived alleles -> deepest node
    assert_eq!(ranked[0].matched, 2);
    assert!((ranked[0].score - 1.0).abs() < 1e-9);
    assert_eq!(ranked[0].lineage, vec!["root", "H", "H2"]);

    let _ = std::fs::remove_file(&samp_path);
}

/// Real-data validation: assign mt + Y haplogroups from a GRCh38-aligned HG002 BAM
/// (chrM = rCRS, chrY = GRCh38 — matching the FTDNA trees). Needs network (live FTDNA
/// fetch). Run: `HG002_B38_BAM=/path/HG002.b38.bam cargo test -p navigator-app --test app \
/// validate_hg002 -- --ignored --nocapture`.
#[tokio::test]
#[ignore = "requires HG002_B38_BAM (GRCh38) + network"]
async fn validate_hg002_haplogroups() {
    let Ok(bam) = std::env::var("HG002_B38_BAM") else {
        eprintln!("HG002_B38_BAM unset — skipping HG002 validation");
        return;
    };
    let app = app().await;
    let b = app.add_biosample(None, "HG002", None, Some("male".into())).await.unwrap();
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: None,
            total_reads: None,
            pf_reads_aligned: None,
            mean_read_length: None,
            mean_insert_size: None,
        })
        .await
        .unwrap();
    let aln = app
        .record_alignment(NewAlignment {
            sequence_run_id: run.id,
            reference_build: "GRCh38".into(),
            aligner: "bwa-mem2".into(),
            variant_caller: None,
            bam_path: Some(bam),
            reference_path: std::env::var("B38_REF").ok(), // needed for the private (de-novo) bucket
        })
        .await
        .unwrap()
        .id;

    let mt = app.assign_mtdna_haplogroup_from_alignment(aln).await.expect("mt assign").ranked;
    let top = &mt[0];
    eprintln!("HG002 mtDNA: {}  ({}/{} mutations, score {:.3})", top.name, top.matched, top.expected, top.score);
    eprintln!("  lineage: {}", top.lineage.join(" › "));
    for r in mt.iter().skip(1).take(3) {
        eprintln!("  alt: {} ({:.3})", r.name, r.score);
    }
    assert!(top.depth > 0 && top.matched > 0, "mt should resolve below root");

    let y = app.assign_y_haplogroup(aln).await.expect("Y assign");
    let top = &y.ranked[0];
    eprintln!("HG002 Y: {}  ({}/{} mutations, score {:.3})", top.name, top.matched, top.expected, top.score);
    eprintln!("  lineage: {}", top.lineage.join(" › "));
    for r in y.ranked.iter().skip(1).take(3) {
        eprintln!("  alt: {} ({:.3})", r.name, r.score);
    }
    // Why descent stopped: child branches and their defining-SNP states.
    use navigator_app::CallState;
    for b in &y.branches {
        eprintln!("  child {} — {}/{} derived:", b.name, b.derived, b.snps.len());
        for s in b.snps.iter().take(8) {
            let st = match s.state {
                CallState::Derived => "DERIVED",
                CallState::Ancestral => "ancestral",
                CallState::NoCall => "no-call",
            };
            eprintln!("      {} {}{}>{}  {}", s.name, s.position, s.ancestral, s.derived, st);
        }
    }
    assert!(top.depth > 0 && top.matched > 0, "Y should resolve below root");

    // Private bucket (de-novo chrY off the backbone) — gated separately (slow + needs ref).
    if std::env::var("PRIVATE_Y").is_ok() {
        use navigator_app::PrivateClass;
        // Y_MASK_BED=path -> external mask; SELF_MASK set -> self-referential; else none.
        let bucket = if std::env::var("SELF_MASK").is_ok() {
            let ivs = app.callable_chr_intervals(aln, "chrY").await.expect("callable intervals");
            let cov: i64 = ivs.iter().map(|(s, e)| e - s).sum();
            eprintln!("Self-referential callable chrY: {} intervals, {} bp", ivs.len(), cov);
            app.private_y_variants_self_masked(aln).await.expect("private Y (self)")
        } else {
            let mask = std::env::var("Y_MASK_BED").ok().map(std::path::PathBuf::from);
            app.private_y_variants(aln, mask.as_deref()).await.expect("private Y")
        };
        eprintln!("Private Y below {}: {} novel, {} off-path", bucket.terminal, bucket.novel(), bucket.off_path());
        for v in bucket.variants.iter().filter(|v| matches!(v.class, PrivateClass::OffPathKnown(_))).take(12) {
            if let PrivateClass::OffPathKnown(n) = &v.class {
                eprintln!("  off-path {} {}>{} d{} -> {}", v.position, v.reference, v.alternate, v.depth, n);
            }
        }
        for v in bucket.variants.iter().filter(|v| v.class == PrivateClass::Novel).take(12) {
            eprintln!("  novel    {} {}>{} d{}", v.position, v.reference, v.alternate, v.depth);
        }
        assert!(!bucket.variants.is_empty(), "expected some off-backbone calls");
    }
}

#[tokio::test]
async fn haplogroup_consensus_combines_recorded_calls() {
    use navigator_app::{CompatibilityLevel, DnaType};
    use navigator_domain::reconciliation::RunHaplogroupCall;
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();

    // Two sources on one path: confident short-read at R-FGC29067, tentative deeper HiFi.
    for (key, label, hg, lineage, score) in [
        ("aln:1", "wgs", "R-FGC29067", vec!["root", "R", "R-FGC29067"], 0.75),
        ("aln:2", "hifi", "R-FGC29071", vec!["root", "R", "R-FGC29067", "R-FGC29071"], 0.54),
    ] {
        let call = RunHaplogroupCall {
            source_label: label.into(),
            haplogroup: hg.into(),
            lineage: lineage.iter().map(|s| s.to_string()).collect(),
            score,
            matched: 0,
            expected: 0,
        };
        app.record_haplogroup_call(subject.guid, DnaType::Y, key, &call).await.unwrap();
    }

    let c = app.haplogroup_consensus(subject.guid, DnaType::Y).await.unwrap().unwrap();
    assert_eq!(c.haplogroup, "R-FGC29067"); // confident node, not the tentative deeper one
    assert_eq!(c.compatibility, CompatibilityLevel::Compatible);
    assert_eq!(c.run_count, 2);
    assert_eq!(c.warnings.len(), 1); // flags the deeper HiFi placement

    // re-recording the same source key replaces (no duplicate)
    let calls = app.haplogroup_calls(subject.guid, DnaType::Y).await.unwrap();
    assert_eq!(calls.len(), 2);
    // mt has nothing recorded
    assert!(app.haplogroup_consensus(subject.guid, DnaType::Mt).await.unwrap().is_none());

    // manual override replaces the computed consensus and is flagged + audited.
    app.set_manual_override(subject.guid, DnaType::Y, "R-FGC29071", Some("Sanger-confirmed")).await.unwrap();
    let o = app.haplogroup_consensus(subject.guid, DnaType::Y).await.unwrap().unwrap();
    assert_eq!(o.haplogroup, "R-FGC29071");
    assert!(o.overridden);
    assert!(o.warnings.iter().any(|w| w.contains("Sanger-confirmed")));

    app.clear_manual_override(subject.guid, DnaType::Y).await.unwrap();
    let back = app.haplogroup_consensus(subject.guid, DnaType::Y).await.unwrap().unwrap();
    assert_eq!(back.haplogroup, "R-FGC29067"); // back to computed
    assert!(!back.overridden);

    // audit recorded the recordings + override + clear
    let audit = app.reconciliation_audit(subject.guid, DnaType::Y).await.unwrap();
    assert!(audit.iter().any(|e| e.action == "MANUAL_OVERRIDE"));
    assert!(audit.iter().any(|e| e.action == "OVERRIDE_CLEARED"));
    assert!(audit.iter().filter(|e| e.action == "RUN_RECORDED").count() >= 2);
}

#[tokio::test]
async fn assign_haplogroup_from_alignment_calls_and_ranks() {
    // Uses the chrM coverage fixture as a stand-in alignment; the reference is ACGTACGT…,
    // so the consensus base at positions 1 and 5 is 'A' (non-variant sites).
    let app = app().await;
    let dir = fixtures();
    let b = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: None,
            total_reads: None,
            pf_reads_aligned: None,
            mean_read_length: None,
            mean_insert_size: None,
        })
        .await
        .unwrap();
    let aln = app
        .record_alignment(NewAlignment {
            sequence_run_id: run.id,
            reference_build: "chrM".into(),
            aligner: "synthetic".into(),
            variant_caller: None,
            bam_path: Some(dir.join("coverage.bam").to_string_lossy().into_owned()),
            reference_path: Some(dir.join("ref.fa").to_string_lossy().into_owned()),
        })
        .await
        .unwrap()
        .id;

    // root --A@1--> N1 --A@5--> N2 ; the sample carries 'A' at both -> N2 is best.
    let tree = r#"{"allNodes":{
        "1":{"haplogroupId":1,"name":"root","isRoot":true,"variants":[],"children":[2]},
        "2":{"haplogroupId":2,"name":"N1","isRoot":false,"variants":[{"variant":"x1A","position":1,"ancestral":"C","derived":"A"}],"children":[3]},
        "3":{"haplogroupId":3,"name":"N2","isRoot":false,"variants":[{"variant":"x5A","position":5,"ancestral":"C","derived":"A"}],"children":[]}
    }}"#;

    let ranked = app.assign_haplogroup_from_alignment(aln, "chrM", tree).await.unwrap().ranked;
    assert_eq!(ranked[0].name, "N2");
    assert_eq!(ranked[0].matched, 2);
    assert!((ranked[0].score - 1.0).abs() < 1e-9);
    assert_eq!(ranked[0].lineage, vec!["root", "N1", "N2"]);
}

#[tokio::test]
async fn add_data_detects_and_routes() {
    use navigator_app::DetectedData;
    let app = app().await;
    let subject = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let dir = std::env::temp_dir();

    // An STR table -> StrProfile, stored under the subject's STR profiles.
    let str_path = dir.join(format!("data-str-{}.csv", subject.guid.0));
    std::fs::write(&str_path, "Marker,Value\nDYS393,13\nDYS390,24\nDYS19,14\nDYS391,11\nDYS385,11-14\n").unwrap();
    assert_eq!(app.add_data(subject.guid, &str_path).await.unwrap(), DetectedData::StrProfile);
    assert_eq!(app.list_str_profiles(subject.guid).await.unwrap().len(), 1);

    // A 23andMe-style export -> ChipData.
    let chip_path = dir.join(format!("data-genome-{}.txt", subject.guid.0));
    std::fs::write(
        &chip_path,
        "# 23andMe\nrsid\tchromosome\tposition\tgenotype\nrs4477212\t1\t82154\tAA\nrs3094315\t1\t752566\tAG\n",
    )
    .unwrap();
    assert_eq!(app.add_data(subject.guid, &chip_path).await.unwrap(), DetectedData::ChipData);
    assert_eq!(app.list_chip_profiles(subject.guid).await.unwrap().len(), 1);

    // A BAM is rejected (it belongs to a sequencing test).
    let bam = dir.join(format!("data-{}.bam", subject.guid.0));
    std::fs::write(&bam, b"\x1f\x8b").unwrap();
    assert!(matches!(app.add_data(subject.guid, &bam).await, Err(AppError::Import(_))));

    for p in [str_path, chip_path, bam] {
        let _ = std::fs::remove_file(p);
    }
}

/// Create a sample → run → alignment chain and return the alignment id.
async fn alignment_id(app: &App) -> i64 {
    let b = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: None,
            total_reads: None,
            pf_reads_aligned: None,
            mean_read_length: None,
            mean_insert_size: None,
        })
        .await
        .unwrap();
    app.record_alignment(NewAlignment {
        sequence_run_id: run.id,
        reference_build: "chrM-fixture".into(),
        aligner: "synthetic".into(),
        variant_caller: None, bam_path: None, reference_path: None,
    })
    .await
    .unwrap()
    .id
}

#[tokio::test]
async fn command_flow_and_overview() {
    let app = app().await;
    let p = app
        .create_project(NewProject { name: "Trio".into(), description: None, administrator: "jk".into() })
        .await
        .unwrap();

    let b1 = app.add_biosample(Some(p.id), "HG002", Some("SAMEA1".into()), Some("male".into())).await.unwrap();
    app.add_biosample(Some(p.id), "HG003", None, Some("female".into())).await.unwrap();

    let overview = app.project_overview().await.unwrap();
    assert_eq!(overview.len(), 1);
    assert_eq!(overview[0].project, p);
    assert_eq!(overview[0].sample_count, 2);

    // chain a run + alignment off the first sample
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b1.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: Some("PAIRED".into()),
            total_reads: Some(8_000_000),
            pf_reads_aligned: Some(7_956_881),
            mean_read_length: Some(148.0),
            mean_insert_size: Some(580.7),
        })
        .await
        .unwrap();
    let aln = app
        .record_alignment(NewAlignment {
            sequence_run_id: run.id,
            reference_build: "chm13v2.0".into(),
            aligner: "bwa".into(),
            variant_caller: None, bam_path: None, reference_path: None,
        })
        .await
        .unwrap();
    assert_eq!(aln.sequence_run_id, run.id);
}

#[tokio::test]
async fn add_biosample_to_missing_project_is_not_found() {
    let app = app().await;
    let err = app.add_biosample(Some(123), "HG002", None, None).await;
    assert!(matches!(err, Err(AppError::Store(navigator_store::StoreError::NotFound(_)))), "got {err:?}");
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct CoverageSummary {
    mean_coverage: f64,
    callable_bases: u64,
}

#[tokio::test]
async fn typed_analysis_artifact_round_trips_and_versions() {
    let app = app().await;
    let b = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: None,
            total_reads: None,
            pf_reads_aligned: None,
            mean_read_length: None,
            mean_insert_size: None,
        })
        .await
        .unwrap();
    let aln = app
        .record_alignment(NewAlignment {
            sequence_run_id: run.id,
            reference_build: "chm13v2.0".into(),
            aligner: "bwa".into(),
            variant_caller: None, bam_path: None, reference_path: None,
        })
        .await
        .unwrap();

    let summary = CoverageSummary { mean_coverage: 178.81, callable_bases: 16_292 };
    app.save_analysis(aln.id, "coverage", "walker-v1", &summary).await.unwrap();

    let loaded: CoverageSummary = app.load_analysis(aln.id, "coverage", "walker-v1").await.unwrap().unwrap();
    assert_eq!(loaded, summary);

    // a different version is absent until written
    let v2: Option<CoverageSummary> = app.load_analysis(aln.id, "coverage", "walker-v2").await.unwrap();
    assert!(v2.is_none());
}

#[tokio::test]
async fn run_coverage_persists_and_reads_back_from_cache() {
    let app = app().await;
    let aln = alignment_id(&app).await;
    let dir = fixtures();

    assert!(app.cached_coverage(aln).await.unwrap().is_none()); // cold

    let result = app
        .run_coverage(aln, dir.join("coverage.bam"), dir.join("ref.fa"), None, CallableLociParams::default())
        .await
        .unwrap();
    assert_eq!(result.genome_territory, 50); // chrM fixture
    assert_eq!(result.callable_bases, 10);

    // now cached for this version (integer fields exact; floats survive round-trip to
    // ~1 ULP, so compare those approximately rather than with fragile float ==)
    let cached = app.cached_coverage(aln).await.unwrap().unwrap();
    assert_eq!(cached.genome_territory, result.genome_territory);
    assert_eq!(cached.callable_bases, result.callable_bases);
    assert_eq!(cached.contig_callable, result.contig_callable);
    assert_eq!(cached.coverage_histogram, result.coverage_histogram);
    assert!((cached.mean_coverage - result.mean_coverage).abs() < 1e-9);

    // re-running is idempotent (upsert in place; store-layer test covers row count)
    let rerun = app
        .run_coverage(aln, dir.join("coverage.bam"), dir.join("ref.fa"), None, CallableLociParams::default())
        .await
        .unwrap();
    assert_eq!(rerun, result);
}

#[tokio::test]
async fn run_denovo_caller_persists_snp_calls() {
    let app = app().await;
    let aln = alignment_id(&app).await;
    let dir = fixtures();

    let calls = app
        .run_denovo_caller(aln, dir.join("coverage.bam"), dir.join("ref.fa"), "chrM".into(), HaploidCallerParams::default())
        .await
        .unwrap();
    // fixture: ref ACGT.. with all-A reads -> SNPs where ref != A at depth>=4
    assert_eq!(calls.iter().map(|c| c.position).collect::<Vec<_>>(), vec![2, 3, 4, 6, 7, 8, 10]);

    let cached = app.cached_denovo(aln, "chrM").await.unwrap().unwrap();
    assert_eq!(cached, calls);
    // a different contig has no cached result
    assert!(app.cached_denovo(aln, "chrY").await.unwrap().is_none());
}

/// Build a sample → run → alignment chain whose BAM is the diploid fixture, return id.
async fn diploid_alignment(app: &App) -> i64 {
    let b = app.add_biosample(None, "diploid", None, None).await.unwrap();
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: None,
            total_reads: None,
            pf_reads_aligned: None,
            mean_read_length: None,
            mean_insert_size: None,
        })
        .await
        .unwrap();
    let bam = fixtures().join("diploid.bam").to_string_lossy().into_owned();
    app.record_alignment(NewAlignment {
        sequence_run_id: run.id,
        reference_build: "chr1".into(),
        aligner: "synthetic".into(),
        variant_caller: None,
        bam_path: Some(bam),
        reference_path: None,
    })
    .await
    .unwrap()
    .id
}

#[tokio::test]
async fn publish_coverage_summary_requires_cached_coverage() {
    let app = app().await;
    let aln = diploid_alignment(&app).await; // has a BAM but no coverage run
    // Bearer client is never reached — the missing-coverage check fails first.
    let client = navigator_app::PdsClient::bearer(reqwest::Client::new(), "http://127.0.0.1:1", "did:plc:x", "tok");
    let err = app.publish_coverage_summary(&client, aln).await;
    assert!(
        matches!(err, Err(navigator_app::AppError::Store(navigator_store::StoreError::NotFound(_)))),
        "got {err:?}"
    );
}

/// Full path: run coverage on the fixture → publish the summary (a real CoverageResult,
/// floats encoded as strings) to a live PDS via a throwaway Bearer account.
#[tokio::test]
#[ignore = "requires PDS_TEST_URL (local atproto PDS container)"]
async fn publish_coverage_summary_to_live_pds() {
    let Ok(pds) = std::env::var("PDS_TEST_URL") else {
        eprintln!("PDS_TEST_URL unset — skipping live publish test");
        return;
    };
    let pds = pds.trim_end_matches('/').to_string();
    let app = app().await;
    let dir = fixtures();
    let aln = alignment_id(&app).await; // bam = coverage.bam, ref = ref.fa, build = chrM-fixture
    app.run_coverage(aln, dir.join("coverage.bam"), dir.join("ref.fa"), None, CallableLociParams::default())
        .await
        .expect("run_coverage");

    let client = live_bearer_client(&pds).await;
    let r = app.publish_coverage_summary(&client, aln).await.expect("publish coverage summary");
    assert!(r.uri.starts_with("at://"), "uri: {}", r.uri);
    eprintln!("✓ published coverage summary {}", r.uri);
}

/// Create a throwaway PDS account and return a Bearer client for it (live tests).
async fn live_bearer_client(pds: &str) -> navigator_app::PdsClient {
    let http = reqwest::Client::new();
    let n = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos() % 1_000_000_000;
    let acct: serde_json::Value = http
        .post(format!("{pds}/xrpc/com.atproto.server.createAccount"))
        .json(&serde_json::json!({ "handle": format!("navp{n}.pds.test"), "email": format!("navp{n}@example.test"), "password": "navp-pw-123456" }))
        .send()
        .await
        .expect("createAccount")
        .json()
        .await
        .expect("createAccount json");
    navigator_app::PdsClient::bearer(http, pds, acct["did"].as_str().unwrap(), acct["accessJwt"].as_str().unwrap())
}

#[tokio::test]
async fn publish_without_login_is_not_authenticated() {
    let app = app().await;
    assert_eq!(app.current_account(), None);
    // Both convenience publishers refuse before sign-in (no keychain access needed).
    assert!(matches!(app.publish_coverage(1).await, Err(navigator_app::AppError::NotAuthenticated)));
    assert!(matches!(
        app.publish_variants(1, "chrM").await,
        Err(navigator_app::AppError::NotAuthenticated)
    ));
}

#[tokio::test]
async fn publish_private_variants_requires_cached_calls() {
    let app = app().await;
    let aln = diploid_alignment(&app).await; // no de-novo run
    let client = navigator_app::PdsClient::bearer(reqwest::Client::new(), "http://127.0.0.1:1", "did:plc:x", "tok");
    let err = app.publish_private_variants(&client, aln, "chrM").await;
    assert!(
        matches!(err, Err(navigator_app::AppError::Store(navigator_store::StoreError::NotFound(_)))),
        "got {err:?}"
    );
}

/// Full path: run de-novo on the fixture → publish the private-variants record (with
/// allele_fraction as a string) to a live PDS, read it back.
#[tokio::test]
#[ignore = "requires PDS_TEST_URL (local atproto PDS container)"]
async fn publish_private_variants_to_live_pds() {
    let Ok(pds) = std::env::var("PDS_TEST_URL") else {
        eprintln!("PDS_TEST_URL unset — skipping live private-variants publish test");
        return;
    };
    let pds = pds.trim_end_matches('/').to_string();
    let app = app().await;
    let dir = fixtures();
    let aln = alignment_id(&app).await;
    app.run_denovo_caller(aln, dir.join("coverage.bam"), dir.join("ref.fa"), "chrM".into(), HaploidCallerParams::default())
        .await
        .expect("run de-novo");

    let client = live_bearer_client(&pds).await;
    let r = app.publish_private_variants(&client, aln, "chrM").await.expect("publish private variants");
    assert!(r.uri.starts_with("at://"), "uri: {}", r.uri);

    let got = client.get_record(navigator_app::PRIVATE_VARIANTS_COLLECTION, r.rkey()).await.expect("getRecord");
    assert_eq!(got["value"]["contig"], "chrM");
    assert_eq!(got["value"]["variants"].as_array().unwrap().len(), 7); // fixture de-novo
    assert!(got["value"]["variants"][0]["alleleFraction"].is_string());
    eprintln!("✓ published private variants {}", r.uri);
}

#[tokio::test]
async fn panel_genotyping_then_ibd_compare() {
    use navigator_analysis::ibd::IbdDetectorConfig;
    use navigator_domain::workspace::PanelSite;

    let app = app().await;
    let site = |pos, r: &str, a: &str| PanelSite {
        chrom: "chr1".into(),
        position: pos,
        reference_allele: r.into(),
        alternate_allele: a.into(),
        name: format!("s{pos}"),
    };
    // The four informative sites in the diploid fixture: hom-ref, het, het, hom-alt.
    let sites = vec![site(1, "A", "G"), site(2, "C", "G"), site(5, "A", "T"), site(8, "T", "A")];

    let panel = app.import_panel("test-panel", &sites).await.unwrap();
    assert_eq!(app.panel_site_count(panel.id).await.unwrap(), 4);

    let aln = diploid_alignment(&app).await;
    let genos = app.genotype_panel(aln, panel.id, 2).await.unwrap();
    let dosages: Vec<i32> = genos.iter().map(|g| g.dosage).collect();
    assert_eq!(dosages, vec![0, 1, 1, 2]);

    // cached read-back
    assert_eq!(app.cached_panel_genotypes(aln, panel.id, 2).await.unwrap().unwrap(), genos);

    // IBD self-compare with relaxed thresholds (only 4 sites): one fully-shared segment.
    let cfg = IbdDetectorConfig { min_snp_count: 3, window_size: 3, min_segment_cm: 0.0, ..IbdDetectorConfig::default() };
    let cmp = app.compare_ibd(aln, aln, panel.id, 2, cfg).await.unwrap();
    assert_eq!(cmp.segments.len(), 1);
    assert!(cmp.summary.total_shared_cm >= 0.0);

    // comparing against an un-genotyped alignment errors clearly.
    let other = diploid_alignment(&app).await;
    assert!(matches!(app.compare_ibd(aln, other, panel.id, 2, cfg).await, Err(AppError::NotGenotyped(_))));
}

#[tokio::test]
async fn import_project_dir_creates_rows_is_idempotent_and_coverage_runs_on_cram() {
    let app = app().await;
    let fx = fixtures();

    // Build a temp project tree: <root>/HG00096/HG00096.chm13.cram(+.crai), reusing the
    // committed CRAM fixture (the .crai is index-by-offset, so the rename is fine).
    let root = std::env::temp_dir().join(format!("dun-import-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let sample = root.join("HG00096");
    std::fs::create_dir_all(&sample).unwrap();
    std::fs::copy(fx.join("coverage.cram"), sample.join("HG00096.chm13.cram")).unwrap();
    std::fs::copy(fx.join("coverage.cram.crai"), sample.join("HG00096.chm13.cram.crai")).unwrap();

    let reference = fx.join("ref.fa");
    let summary = app.import_project_dir(&root, Some(reference.clone()), "tester".into()).await.unwrap();
    assert_eq!(summary.samples_total, 1);
    assert_eq!(summary.samples_created, 1);
    assert_eq!(summary.alignments_created, 1);
    assert_eq!(summary.alignments_skipped, 0);
    assert!(summary.missing_index.is_empty());

    let bios = app.list_biosamples(summary.project.id).await.unwrap();
    assert_eq!(bios.len(), 1);
    assert_eq!(bios[0].donor_identifier, "HG00096");

    // Re-import: project/sample/alignment reused, nothing new created.
    let again = app.import_project_dir(&root, Some(reference), "tester".into()).await.unwrap();
    assert_eq!(again.project.id, summary.project.id);
    assert_eq!(again.samples_created, 0);
    assert_eq!(again.alignments_created, 0);
    assert_eq!(again.alignments_skipped, 1);
    assert_eq!(app.project_overview().await.unwrap().len(), 1);

    // Coverage recompute works on the imported CRAM (reference_path was stamped).
    let aln = app.list_all_alignments().await.unwrap();
    assert_eq!(aln.len(), 1);
    assert_eq!(aln[0].reference_build, "chm13v2.0");
    let cov = app.run_coverage_for_alignment(aln[0].id).await.unwrap();
    assert_eq!(cov.genome_territory, 50); // the fixture chrM is 50 bp

    let _ = std::fs::remove_dir_all(&root);
}

#[tokio::test]
async fn project_report_rolls_up_coverage_and_csv_round_trips() {
    let app = app().await;
    let fx = fixtures();

    let root = std::env::temp_dir().join(format!("dun-report-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let sample = root.join("HG00096");
    std::fs::create_dir_all(&sample).unwrap();
    std::fs::copy(fx.join("coverage.cram"), sample.join("HG00096.chm13.cram")).unwrap();
    std::fs::copy(fx.join("coverage.cram.crai"), sample.join("HG00096.chm13.cram.crai")).unwrap();

    let summary = app.import_project_dir(&root, Some(fx.join("ref.fa")), "tester".into()).await.unwrap();
    let pid = summary.project.id;

    // Before coverage runs: report has the sample, coverage cells empty, haplogroups none.
    let before = app.project_report(pid).await.unwrap();
    assert_eq!(before.len(), 1);
    assert_eq!(before[0].alignment_count, 1);
    assert!(before[0].mean_coverage.is_none());
    assert!(before[0].y_haplogroup.is_none() && before[0].mt_haplogroup.is_none());

    // Run coverage, then the report fills in.
    let aln = app.list_all_alignments().await.unwrap();
    app.run_coverage_for_alignment(aln[0].id).await.unwrap();
    let after = app.project_report(pid).await.unwrap();
    assert!(after[0].mean_coverage.is_some());
    assert_eq!(after[0].callable_bases, Some(10)); // fixture: 10 callable bases

    // CSV: header + one data row, sample id present.
    let csv = navigator_app::report_csv(&after);
    let lines: Vec<&str> = csv.lines().collect();
    assert_eq!(lines.len(), 2);
    assert!(lines[0].starts_with("sample_id,alignment_count,mean_coverage"));
    assert!(lines[1].starts_with("HG00096,1,"));

    let _ = std::fs::remove_dir_all(&root);
}

#[tokio::test]
async fn import_without_reference_resolves_from_cache_else_reports_needed() {
    use navigator_app::AppError;

    // Point the gateway cache at a temp dir; no network involved.
    let cache = std::env::temp_dir().join(format!("dun-refcache-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&cache);
    let app = app_with_ref_cache(&cache).await;
    let fx = fixtures();
    let root = std::env::temp_dir().join(format!("dun-import-noref-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let sample = root.join("HG00096");
    std::fs::create_dir_all(&sample).unwrap();
    std::fs::copy(fx.join("coverage.cram"), sample.join("HG00096.chm13.cram")).unwrap();
    std::fs::copy(fx.join("coverage.cram.crai"), sample.join("HG00096.chm13.cram.crai")).unwrap();

    // Empty cache → import (no explicit reference) reports the chm13v2.0 build is needed, no writes.
    match app.import_project_dir(&root, None, "tester".into()).await {
        Err(AppError::ReferenceNeeded(needs)) => {
            assert_eq!(needs.len(), 1);
            assert_eq!(needs[0].build, "chm13v2.0");
            assert!(needs[0].url.ends_with("chm13v2.0.fa.gz"));
        }
        other => panic!("expected ReferenceNeeded, got {other:?}"),
    }
    assert!(app.project_overview().await.unwrap().is_empty(), "no writes on ReferenceNeeded");

    // Seed the cache as if a download had completed (reuse the fixture ref as chm13v2.0).
    let refs = cache.join("references");
    std::fs::create_dir_all(&refs).unwrap();
    std::fs::copy(fx.join("ref.fa"), refs.join("chm13v2.0.fa")).unwrap();
    std::fs::copy(fx.join("ref.fa.fai"), refs.join("chm13v2.0.fa.fai")).unwrap();

    // Now import (no explicit reference) resolves from the cache and creates rows.
    let summary = app.import_project_dir(&root, None, "tester".into()).await.unwrap();
    assert_eq!(summary.alignments_created, 1);
    let aln = app.list_all_alignments().await.unwrap();
    assert_eq!(aln[0].reference_path.as_deref(), Some(refs.join("chm13v2.0.fa").to_string_lossy().as_ref()));
    // Coverage runs on the CRAM using the cache-resolved reference.
    app.run_coverage_for_alignment(aln[0].id).await.unwrap();

    std::env::remove_var("NAVIGATOR_REFGENOME_DIR");
    let _ = std::fs::remove_dir_all(&root);
    let _ = std::fs::remove_dir_all(&cache);
}

#[tokio::test]
async fn assign_y_haplogroup_lifts_grch38_tree_onto_chm13_alignment() {
    // Seed a GRCh38→chm13v2.0 chain: chrY t[100,200) → chrY q[0,100). So 1-based tree
    // positions 101 & 105 lift (lift p-1, +1 back) to ychr.bam positions 1 & 5, where the
    // fixture has 'A' callable. The chain is pre-seeded so resolve_chain is a cache hit.
    let cache = std::env::temp_dir().join(format!("dun-lift-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&cache);
    let chains = cache.join("liftover");
    std::fs::create_dir_all(&chains).unwrap();
    std::fs::write(
        chains.join("GRCh38-to-chm13v2.0.chain"),
        "chain 1 chrY 1000 + 100 200 chrY 1000 + 0 100 1\n100\n",
    )
    .unwrap();

    let app = app_with_ref_cache(&cache).await;
    let dir = fixtures();
    let b = app.add_biosample(None, "HG002", None, None).await.unwrap();
    let run = app
        .record_sequence_run(NewSequenceRun {
            biosample_guid: b.guid,
            platform_name: "ILLUMINA".into(),
            instrument_model: None,
            test_type: "WGS".into(),
            library_layout: None,
            total_reads: None,
            pf_reads_aligned: None,
            mean_read_length: None,
            mean_insert_size: None,
        })
        .await
        .unwrap();
    let aln = app
        .record_alignment(NewAlignment {
            sequence_run_id: run.id,
            reference_build: "chm13v2.0".into(), // triggers GRCh38→CHM13 liftover for chrY
            aligner: "synthetic".into(),
            variant_caller: None,
            bam_path: Some(dir.join("ychr.bam").to_string_lossy().into_owned()),
            reference_path: None,
        })
        .await
        .unwrap()
        .id;

    // GRCh38-coordinate tree: root --A@101--> N1 --A@105--> N2.
    let tree = r#"{"allNodes":{
        "1":{"haplogroupId":1,"name":"root","isRoot":true,"variants":[],"children":[2]},
        "2":{"haplogroupId":2,"name":"N1","isRoot":false,"variants":[{"variant":"y101","position":101,"ancestral":"C","derived":"A"}],"children":[3]},
        "3":{"haplogroupId":3,"name":"N2","isRoot":false,"variants":[{"variant":"y105","position":105,"ancestral":"C","derived":"A"}],"children":[]}
    }}"#;

    let ranked = app.assign_haplogroup_from_alignment(aln, "chrY", tree).await.unwrap().ranked;
    assert_eq!(ranked[0].name, "N2", "lifted GRCh38 positions found the derived alleles on CHM13 chrY");
    assert_eq!(ranked[0].matched, 2);
    assert!((ranked[0].score - 1.0).abs() < 1e-9);

    let _ = std::fs::remove_dir_all(&cache);
}
