package com.decodingus.ancestry.report

import com.decodingus.ancestry.model.*
import io.circe.syntax.*

import java.io.{File, PrintWriter}
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import scala.util.Using

/**
 * Generates ancestry analysis reports in various formats.
 */
object AncestryReportWriter {

  /**
   * Write a text report summarizing ancestry results.
   */
  def writeReport(outputDir: File, result: AncestryResult, panelType: AncestryPanelType): Unit = {
    val reportFile = new File(outputDir, s"ancestry_${result.panelType}_report.txt")

    Using.resource(new PrintWriter(reportFile)) { writer =>
      writer.println("=" * 60)
      writer.println("ANCESTRY ANALYSIS REPORT")
      writer.println("=" * 60)
      writer.println()
      writer.println(s"Analysis Date: ${LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)}")
      writer.println(s"Panel Type: ${result.panelType}")
      writer.println(s"Analysis Version: ${result.analysisVersion}")
      writer.println(s"Reference Version: ${result.referenceVersion}")
      writer.println()

      // Data quality
      writer.println("-" * 40)
      writer.println("DATA QUALITY")
      writer.println("-" * 40)
      writer.println(f"SNPs Analyzed: ${result.snpsAnalyzed}%,d")
      writer.println(f"SNPs with Genotype: ${result.snpsWithGenotype}%,d")
      writer.println(f"SNPs Missing: ${result.snpsMissing}%,d")
      writer.println(f"Call Rate: ${result.snpsWithGenotype.toDouble / result.snpsAnalyzed * 100}%.1f%%")
      writer.println(f"Confidence Level: ${result.confidenceLevel * 100}%.1f%%")
      writer.println()

      // Super-population summary
      writer.println("-" * 40)
      writer.println("CONTINENTAL ANCESTRY SUMMARY")
      writer.println("-" * 40)
      result.superPopulationSummary
        .filter(_.percentage >= 0.5)
        .foreach { sp =>
          writer.println(f"${sp.superPopulation}%-20s ${sp.percentage}%6.1f%%")
        }
      writer.println()

      // Detailed population breakdown
      writer.println("-" * 40)
      writer.println("DETAILED POPULATION BREAKDOWN")
      writer.println("-" * 40)
      writer.println(f"${"Rank"}%-5s ${"Population"}%-25s ${"Percentage"}%-12s ${"95% CI"}")
      writer.println("-" * 60)

      result.percentages
        .filter(_.percentage >= 0.5)
        .foreach { p =>
          writer.println(f"${p.rank}%-5d ${p.populationName}%-25s ${p.percentage}%6.1f%%       " +
            f"(${p.confidenceLow}%.1f%% - ${p.confidenceHigh}%.1f%%)")
        }
      writer.println()

      // Primary ancestry
      val primary = AncestryResult.primaryAncestry(result)
      val admixed = AncestryResult.isAdmixed(result)

      writer.println("-" * 40)
      writer.println("SUMMARY")
      writer.println("-" * 40)
      writer.println(s"Primary Ancestry: ${primary.getOrElse("Unknown")}")
      writer.println(s"Admixed: ${if (admixed) "Yes" else "No"}")

      if (admixed) {
        val significantPops = result.superPopulationSummary.filter(_.percentage >= 10.0)
        writer.println(s"Major Components: ${significantPops.map(sp => f"${sp.superPopulation} (${sp.percentage}%.0f%%)").mkString(", ")}")
      }

      writer.println()
      writer.println("=" * 60)
      writer.println("Report generated by Decoding-Us Navigator")
      writer.println("https://decoding.us")
      writer.println("=" * 60)
    }
  }

  /**
   * Write JSON report for programmatic access.
   */
  def writeJsonReport(outputDir: File, result: AncestryResult): Unit = {
    val jsonFile = new File(outputDir, s"ancestry_${result.panelType}.json")

    Using.resource(new PrintWriter(jsonFile)) { writer =>
      writer.println(result.asJson.spaces2)
    }
  }

  /**
   * Write HTML report with visualizations.
   */
  def writeHtmlReport(outputDir: File, result: AncestryResult): Unit = {
    val htmlFile = new File(outputDir, s"ancestry_${result.panelType}_report.html")

    Using.resource(new PrintWriter(htmlFile)) { writer =>
      writer.println(
        s"""<!DOCTYPE html>
           |<html>
           |<head>
           |  <title>Ancestry Analysis Report</title>
           |  <style>
           |    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; }
           |    h1 { color: #333; }
           |    .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0; }
           |    .chart { display: flex; align-items: center; margin: 10px 0; }
           |    .bar { height: 24px; border-radius: 4px; }
           |    .label { width: 200px; }
           |    .pct { width: 60px; text-align: right; margin-left: 10px; }
           |    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
           |    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
           |    th { background: #f5f5f5; }
           |    .confidence { color: #666; font-size: 0.9em; }
           |  </style>
           |</head>
           |<body>
           |  <h1>Ancestry Analysis Report</h1>
           |
           |  <div class="summary">
           |    <strong>Panel:</strong> ${result.panelType}|
           |    <strong>SNPs:</strong> ${result.snpsWithGenotype} / ${result.snpsAnalyzed}|
           |    <strong>Confidence:</strong> ${f"${result.confidenceLevel * 100}%.0f"}%
           |  </div>
           |
           |  <h2>Continental Ancestry</h2>
           |  ${renderSuperPopulationBars(result)}
           |
           |  <h2>Detailed Breakdown</h2>
           |  ${renderPopulationTable(result)}
           |
           |  <footer style="margin-top: 40px; color: #999; font-size: 0.9em;">
           |    Generated by Decoding-Us Navigator | ${LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE)}
           |  </footer>
           |</body>
           |</html>
           |""".stripMargin
      )
    }
  }

  private def renderSuperPopulationBars(result: AncestryResult): String = {
    val colors = Map(
      "European" -> "#3366CC",
      "African" -> "#FF6600",
      "East Asian" -> "#00CC00",
      "South Asian" -> "#9900CC",
      "Americas" -> "#CC0066",
      "West Asian" -> "#996633",
      "Oceanian" -> "#009999",
      "Central Asian" -> "#66CCCC",
      "Native American" -> "#990033"
    )

    result.superPopulationSummary
      .filter(_.percentage >= 0.5)
      .map { sp =>
        val color = colors.getOrElse(sp.superPopulation, "#888888")
        s"""<div class="chart">
           |  <span class="label">${sp.superPopulation}</span>
           |  <div class="bar" style="width: ${sp.percentage * 3}px; background: $color;"></div>
           |  <span class="pct">${f"${sp.percentage}%.1f"}%</span>
           |</div>""".stripMargin
      }
      .mkString("\n")
  }

  private def renderPopulationTable(result: AncestryResult): String = {
    val rows = result.percentages
      .filter(_.percentage >= 0.5)
      .map { p =>
        s"""<tr>
           |  <td>${p.rank}</td>
           |  <td>${p.populationName}</td>
           |  <td>${f"${p.percentage}%.1f"}%</td>
           |  <td class="confidence">${f"${p.confidenceLow}%.1f"}% - ${f"${p.confidenceHigh}%.1f"}%</td>
           |</tr>""".stripMargin
      }
      .mkString("\n")

    s"""<table>
       |  <thead>
       |    <tr><th>Rank</th><th>Population</th><th>Percentage</th><th>95% CI</th></tr>
       |  </thead>
       |  <tbody>
       |    $rows
       |  </tbody>
       |</table>""".stripMargin
  }
}
