package com.decodingus.util

import munit.FunSuite
import java.io.{File, PrintWriter}
import java.nio.file.Files

class CsvFingerprinterSpec extends FunSuite {

  private def withTempFile(content: String, extension: String = ".csv")(test: File => Unit): Unit = {
    val file = Files.createTempFile("fingerprint_test", extension).toFile
    try {
      val writer = new PrintWriter(file)
      try {
        writer.write(content)
      } finally {
        writer.close()
      }
      test(file)
    } finally {
      file.delete()
    }
  }

  test("detects BAM files by extension") {
    withTempFile("binary content", ".bam") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.Alignment)
    }
  }

  test("detects CRAM files by extension") {
    withTempFile("binary content", ".cram") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.Alignment)
    }
  }

  test("detects VCF files by extension") {
    withTempFile("##fileformat=VCFv4.2", ".vcf") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.VcfVariants)
    }
  }

  test("detects Y-STR profile with DYS markers") {
    val strContent =
      """Marker,Value
        |DYS393,13
        |DYS390,24
        |DYS19,14
        |DYS391,11
        |DYS385a,11
        |DYS385b,14
        |DYS426,12
        |DYS388,12
        |DYS439,11
        |DYS389I,13
        |DYS392,13
        |DYS389II,29""".stripMargin

    withTempFile(strContent, ".csv") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.StrProfile)
    }
  }

  test("detects Y-STR profile with horizontal format") {
    val strContent =
      """Sample,DYS393,DYS390,DYS19,DYS391,DYS385a,DYS385b,DYS426,DYS388,DYS439,DYS389I,DYS392,DYS389II
        |SAMPLE001,13,24,14,11,11,14,12,12,11,13,13,29""".stripMargin

    withTempFile(strContent, ".csv") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.StrProfile)
    }
  }

  test("detects Y-STR with filename hint") {
    val content =
      """Marker,Value
        |DYS393,13
        |DYS390,24""".stripMargin

    // Create temp file with ystr in name
    val file = Files.createTempFile("ystr_profile", ".csv").toFile
    try {
      val writer = new PrintWriter(file)
      try {
        writer.write(content)
      } finally {
        writer.close()
      }
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.StrProfile)
    } finally {
      file.delete()
    }
  }

  test("detects 23andMe chip data") {
    val chipContent =
      """# This data file generated by 23andMe at: Thu Jan 01 2024
        |#
        |# rsid	chromosome	position	genotype
        |rs4477212	1	82154	AA
        |rs3094315	1	752566	AG
        |rs3131972	1	752721	GG
        |rs12124819	1	776546	AA
        |rs11240777	1	798959	AG
        |rs6681049	1	800007	CC""".stripMargin

    withTempFile(chipContent, ".txt") { file =>
      val result = CsvFingerprinter.fingerprint(file)
      assert(result.isInstanceOf[CsvFileType.ChipData])
      assertEquals(result.asInstanceOf[CsvFileType.ChipData].vendor, Some("23andMe"))
    }
  }

  test("detects AncestryDNA chip data") {
    val chipContent =
      """#AncestryDNA raw data download
        |#This file was generated by AncestryDNA
        |rsid	chromosome	position	allele1	allele2
        |rs4477212	1	82154	A	A
        |rs3094315	1	752566	A	G
        |rs3131972	1	752721	G	G
        |rs12124819	1	776546	A	A
        |rs11240777	1	798959	A	G""".stripMargin

    withTempFile(chipContent, ".txt") { file =>
      val result = CsvFingerprinter.fingerprint(file)
      assert(result.isInstanceOf[CsvFileType.ChipData])
      assertEquals(result.asInstanceOf[CsvFileType.ChipData].vendor, Some("AncestryDNA"))
    }
  }

  test("detects chip data with rsID patterns") {
    val chipContent =
      """RSID,Chromosome,Position,Genotype
        |rs4477212,1,82154,AA
        |rs3094315,1,752566,AG
        |rs3131972,1,752721,GG""".stripMargin

    withTempFile(chipContent, ".csv") { file =>
      val result = CsvFingerprinter.fingerprint(file)
      assert(result.isInstanceOf[CsvFileType.ChipData])
    }
  }

  test("returns Unknown for empty file") {
    withTempFile("", ".csv") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.Unknown)
    }
  }

  test("returns Unknown for unrecognized format") {
    val content =
      """Name,Age,City
        |Alice,30,Boston
        |Bob,25,Seattle""".stripMargin

    withTempFile(content, ".csv") { file =>
      assertEquals(CsvFingerprinter.fingerprint(file), CsvFileType.Unknown)
    }
  }

  test("detects chip data from filename 23andme") {
    val content =
      """rsid	chromosome	position	genotype
        |rs4477212	1	82154	AA
        |rs3094315	1	752566	AG""".stripMargin

    val file = Files.createTempFile("23andme_data", ".txt").toFile
    try {
      val writer = new PrintWriter(file)
      try {
        writer.write(content)
      } finally {
        writer.close()
      }
      val result = CsvFingerprinter.fingerprint(file)
      assert(result.isInstanceOf[CsvFileType.ChipData])
      assertEquals(result.asInstanceOf[CsvFileType.ChipData].vendor, Some("23andMe"))
    } finally {
      file.delete()
    }
  }

  test("isTextFile returns true for CSV files") {
    withTempFile("test", ".csv") { file =>
      assert(CsvFingerprinter.isTextFile(file))
    }
  }

  test("isTextFile returns true for TSV files") {
    withTempFile("test", ".tsv") { file =>
      assert(CsvFingerprinter.isTextFile(file))
    }
  }

  test("isTextFile returns true for TXT files") {
    withTempFile("test", ".txt") { file =>
      assert(CsvFingerprinter.isTextFile(file))
    }
  }

  test("isTextFile returns false for BAM files") {
    withTempFile("test", ".bam") { file =>
      assert(!CsvFingerprinter.isTextFile(file))
    }
  }
}
